### ISSUE TITLE
deserialize_seq and other todo!() deserializers

### ISSUE THREAD

**Issue by simonrupf** [MostlyMax/rsv-rust#1]
Hello and thank you for working on this serde library. I'd be interested to add support for RSV to [convert2json](https://crates.io/crates/convert2json). That project uses various serde deserializers to cast values into a serde_json serializer. I tried using your library to deserialize into a `Vec<HashMap>` like I implemented for the CSV deserialization, so each record would get parsed into some generic JSON object. But ATM it trips up on the `todo!()` macros:

https://github.com/MostlyMax/rsv-rust/blob/7423755af1128820916fc8d71ba7fcc2a48e43bc/src/deserializer.rs#L261C1-L265

Do you intend to continue working on this implementation and/or would you care for PRs or other forms of collaboration on it? I had started working on my own RSV serde library, but hadn't gotten as far as you, yet, so it would probably make sense for me to help getting this one into a state that lets me parse as many of Stenway's examples as is feasible.

**Comment by mostlymaxi** [comment]
Hey! I think it would be great to include rsv as part of serde2json.
Nested structs and vectors were outside the scope of what I was using this at the time for, but I'll take a look and see if it's straightforward to implement - wouldn't mind continuing to maintain this little project.
Would love any PRs or suggestions and am certainly open to collaboration!

**Comment by simonrupf** [comment]
Ok, then I'll give a branch a shot on the weekend and report my progress on Sunday. I assume that once I've got the sequences implemented, there will be others that will be needed, but as a start, parsing a list of empty sequences (i.e. a sample containing only ROW_TERM_BYTEs) would already be progress.

For writing tests, would you prefer them to live in a separate file or prefer them inline, for example right after the function they relate to?

**Comment by simonrupf** [comment]
Made [some minor progress](https://github.com/simonrupf/rsv-rust/commit/f4c24180221b2a2c281703f979795fcafa19310e), it works for empty sequences, but not yet for null bytes or strings. I'll work some more on it and give you another update by next weekend.

**Comment by simonrupf** [comment]
Thank you very much! I've just released [0.9.0 of convert2json](https://github.com/simonrupf/convert2json/releases/tag/0.9.0), which includes an rsv2json and rq binary based on your library.
